### ISSUE TITLE
dependencies vs devDependencies in Project.json 

### ISSUE THREAD

**Issue by MaxterBattle** [rossmoody/ts-extension-starter#3]
Hi Ross,

I'm starting to play with this starter.   Thanks.   The first thing I do is generally check out package.json, and I notice that there are several _dependiencies_ that seem more like _devDependencies_.  The @types packages for example.   If you are looking for PRs I'll contribute.

Background 
=========  
Found you project, seems to fit what I was looking for.   I'm a retired dev, finished my professional career at Microsoft for almost 15 years.  I know typescript and good dev practices pretty well, but react is fairly new to me.   Even at 65, I like learning, just at a slower pace now.

**Comment by rossmoody** [comment]
@MaxterBattle! This is so cool to see you are interested in contributing. High five. 

The devDependency vs regular dependency line has eluded me for years. I think [I've read this StackOverflow 10 times](https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies) and I still mix them up.

It would be so awesome if you want to contribute and anything in regards to correct dependency classification seems like an objective no-brainer improvement. I just sent you a collaborator invite so ya don't have to do lots of forking.

Also, I'm always a fan of non-typical dev origins. I too like learning, and typically at a slower pace since my roots are in letterpress printmaking. Thanks for the issues and pitching in.
